services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_API_TOKEN: ${VITE_API_TOKEN}
    ports:
      - "5173:5173" 